### ISSUE TITLE
Error: Illegal #include (Preprocessor.js:225)

### ISSUE THREAD

**Issue by markusha** [dcodeIO/Preprocessor.js#10]
1. Create a file test.js with the following content:

``` js
// #ifndef TEST
// #define var TEST=true
console.log('test');
// #endif
```
1. Create a file main.js with the following content:

``` js
// #include "test.js"
console.log('testing include');
// #include "test.js"
```
1. Preprocess main.js.

Result:
The file test.js is included twice in the output file.
The following error is shown:

```
C:\programs\nodejs\node_modules\preprocessor\Preprocessor.js:225
                        throw(new Error("Illegal #"+match[2]+": "+this.source.
                              ^
Error: Illegal #include: // #include "test.js
...
    at Preprocessor.process (C:\programs\nodejs\node_modules\preprocessor\Preprocessor.js:225:31)
    at Object.<anonymous> (C:\programs\nodejs\node_modules\preprocessor\bin\preprocess:65:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Expected result:
The file test.js is included only once in the output file.
No errors are shown.

P. S. I see that there's an undocumented directive #include_once for such cases. But still this is an error.

**Comment by markusha** [comment]
My bad. The error was shown due to my slow typing/quick reaction of a script that runs the preprocessor.
But still the file test.js was included twice in the output file.

**Comment by dcodeIO** [comment]
Maybe I miss something, but for a **main.js** with contents

``` js
// #include "test.js"
console.log('testing include');
// #include "test.js"
```

the file **test.js** is of course included twice, while for

``` js
// #include_once "test.js"
console.log('testing include');
// #include_once "test.js"
```

it's not.

**Comment by markusha** [comment]
Ah, again my bad for not specifically describing the problem.
The _file_ **test.js** in this case must indeed be included in **main.js** twice. But the thing is that the _contents_ of the file **test.js**, specifically `console.log('test');`, will be included twice too. Which is an error because `#ifndef` from the second inclusion must prevent this.

**Comment by dcodeIO** [comment]
I see. Well, the issue here is that #define is quite a hack currently and does not play well with #ifdef, which is of course bad and I'd need to invest some time to rethink both.

Personally, I am migrating all my projects to [MetaScript](https://github.com/dcodeIO/MetaScript) currently (e.g. https://github.com/dcodeIO/ByteBuffer.js/tree/master/src), which is a more javascripty way of preprocessing, and I'd recommend that you'd do the same.

**test.js**

``` js
//? if (typeof TEST === 'undefined') { TEST = true;
console.log("test");
//? }
```

**main.js**

``` js
//? include("test.js");
console.log('testing include');
//? include("test.js");
```

which does exactly what you need.

**Comment by markusha** [comment]
> Personally, I am migrating all my projects to MetaScript

Thanks for the tip.
